name: Publish Caching extension to Nuget.org

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.x'
          
    - name: Install dependencies
      run: |
        dotnet restore src/Extensions.Caching.Abstractions/Extensions.Caching.Abstractions.csproj
        dotnet restore src/Extensions.Caching/Extensions.Caching.csproj
        
    - name: Build
      run: |
        dotnet build src/Extensions.Caching.Abstractions/Extensions.Caching.Abstractions.csproj --configuration Release --no-restore
        dotnet build src/Extensions.Caching/Extensions.Caching.csproj --configuration Release --no-restore
        
    - name: Publish to Nuget.org
      run: |
        rm -rf nuget/
        
        dotnet pack --no-build src/Extensions.Caching.Abstractions/Extensions.Caching.Abstractions.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Extensions.Caching/Extensions.Caching.csproj --configuration Release --output nuget
        
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
